name = "BarringtonTheorem"
version = "0.1.0"
defaultTargets = ["BarringtonTheorem"]

[[lean_lib]]
name = "BarringtonTheorem"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.0-rc2"
